<?xml version='1.0' encoding='utf-8'?>
<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><DebugType>portable</DebugType><Configurations>Debug;Release;Release 2;Beta</Configurations></PropertyGroup><ItemGroup /><PropertyGroup Condition=" '$(Configuration)' == 'Debug' "><DefineConstants>DEBUG</DefineConstants></PropertyGroup><PropertyGroup Condition=" '$(Configuration)' == 'Release' "><DefineConstants>RELEASE</DefineConstants></PropertyGroup><PropertyGroup Condition=" '$(Configuration)' == 'Release 2' "><DefineConstants>RELEASE2</DefineConstants></PropertyGroup><PropertyGroup Condition=" '$(Configuration)' == 'Beta' "><DefineConstants>BETA</DefineConstants></PropertyGroup></Project>